export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const GET_ENVIRONMENT_SUCCESS = 'GET_ENVIRONMENT_SUCCESS';
export const GET_ENVIRONMENT_ERRORED = 'GET_ENVIRONMENT_ERRORED';
export const GET_ENVIRONMENT_LOADING = 'GET_ENVIRONMENT_LOADING';

export const GET_FETCHTARGET_SUCCESS = 'GET_FETCHTARGET_SUCCESS';

export const GET_INITIAL_CONVERT_DROPDOWN_DATA_SUCCESS = 'GET_INITIAL_CONVERT_DROPDOWN_DATA_SUCCESS';
export const GET_INITIAL_CONVERT_DROPDOWN_DATA_ERRORED = 'GET_INITIAL_CONVERT_DROPDOWN_DATA_ERRORED';

export const MAP_CONVERTDROPDOWNS_SUCCESS = 'MAP_CONVERTDROPDOWNS_SUCCESS';
export const MAP_CONVERTDROPDOWNS_ERRORED = 'MAP_CONVERTDROPDOWNS_ERRORED';

